package com.android.purebilibili.core.ui.lint

/**
 * Frozen allowlist of feature files that currently contain hardcoded
 * RoundedCornerShape(N) / tween(N) / spring(N) / MaterialTheme.colorScheme.surface
 * usage. Each entry must be removed once the corresponding feature is migrated
 * to AppShapes / AppMotionTokens / AppSurfaceTokens, so the lint tests block
 * the next regression.
 *
 * Adding a new path here is a documented exception, not a default. A PR adding
 * a new entry should explain the pixel-level reason in the description.
 */
internal object StyleLintAllowlist {

    /** 迁移到 AppShapes / MaterialTheme.shapes 后从本表移除. */
    val SHAPE_HITS: Set<String> = setOf(
        "src/main/java/com/android/purebilibili/feature/article/ArticleDetailScreen.kt",
        "src/main/java/com/android/purebilibili/feature/audio/screen/MusicDetailScreen.kt",
        "src/main/java/com/android/purebilibili/feature/bangumi/BangumiDetailScreen.kt",
        "src/main/java/com/android/purebilibili/feature/bangumi/BangumiScreen.kt",
        "src/main/java/com/android/purebilibili/feature/bangumi/MyBangumiScreen.kt",
        "src/main/java/com/android/purebilibili/feature/bangumi/ui/player/BangumiPlayerComponents.kt",
        "src/main/java/com/android/purebilibili/feature/download/BatchDownloadDialog.kt",
        "src/main/java/com/android/purebilibili/feature/download/DirectorySelectionDialog.kt",
        "src/main/java/com/android/purebilibili/feature/download/DownloadListScreen.kt",
        "src/main/java/com/android/purebilibili/feature/download/DownloadQualityDialog.kt",
        "src/main/java/com/android/purebilibili/feature/download/OfflineVideoPlayerScreen.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/ActionButton.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/DynamicCard.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/DynamicCommentSheet.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/DynamicComponents.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/DynamicSidebar.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/ImagePreviewDialog.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/DynamicOpusLinkCard.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/LiveCard.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/RepostDialog.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/VideoCards.kt",
        "src/main/java/com/android/purebilibili/feature/home/components/cards/GlassVideoCard.kt",
        "src/main/java/com/android/purebilibili/feature/home/components/iOSRefreshIndicator.kt",
        "src/main/java/com/android/purebilibili/feature/home/HomeFeedSkeletonCard.kt",
        "src/main/java/com/android/purebilibili/feature/list/CommonListScreen.kt",
        "src/main/java/com/android/purebilibili/feature/live/components/LandscapeChatOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/live/components/LiveChatSection.kt",
        "src/main/java/com/android/purebilibili/feature/live/components/LiveContributionRankSheet.kt",
        "src/main/java/com/android/purebilibili/feature/live/components/LiveInteractionSheets.kt",
        "src/main/java/com/android/purebilibili/feature/live/components/LivePlayerControls.kt",
        "src/main/java/com/android/purebilibili/feature/live/components/LiveSendDanmakuSheet.kt",
        "src/main/java/com/android/purebilibili/feature/live/components/LiveSuperChatSection.kt",
        "src/main/java/com/android/purebilibili/feature/live/LiveAreaDetailScreen.kt",
        "src/main/java/com/android/purebilibili/feature/live/LiveAreaScreen.kt",
        "src/main/java/com/android/purebilibili/feature/live/LiveListScreen.kt",
        "src/main/java/com/android/purebilibili/feature/live/LivePlayerScreen.kt",
        "src/main/java/com/android/purebilibili/feature/live/LiveSearchScreen.kt",
        "src/main/java/com/android/purebilibili/feature/login/LoginComponents.kt",
        "src/main/java/com/android/purebilibili/feature/message/ChatScreen.kt",
        "src/main/java/com/android/purebilibili/feature/message/InboxScreen.kt",
        "src/main/java/com/android/purebilibili/feature/onboarding/OnboardingBottomSheet.kt",
        "src/main/java/com/android/purebilibili/feature/onboarding/OnboardingScreen.kt",
        "src/main/java/com/android/purebilibili/feature/partition/PartitionScreen.kt",
        "src/main/java/com/android/purebilibili/feature/plugin/AdFilterPlugin.kt",
        "src/main/java/com/android/purebilibili/feature/plugin/EyeProtectionOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/plugin/HomeFeedAnonymizerPlugin.kt",
        "src/main/java/com/android/purebilibili/feature/plugin/SponsorBlockPlugin.kt",
        "src/main/java/com/android/purebilibili/feature/profile/OfficialWallpaperSheet.kt",
        "src/main/java/com/android/purebilibili/feature/profile/ProfileScreen.kt",
        "src/main/java/com/android/purebilibili/feature/profile/SplashWallpaperPickerSheet.kt",
        "src/main/java/com/android/purebilibili/feature/profile/WallpaperAdjustmentSheet.kt",
        "src/main/java/com/android/purebilibili/feature/screenshot/AppScreenshotRegionOverlay.kt",

        "src/main/java/com/android/purebilibili/feature/search/SearchScreen.kt",
        "src/main/java/com/android/purebilibili/feature/search/SearchTrendingScreen.kt",
        "src/main/java/com/android/purebilibili/feature/search/TopicDetailScreen.kt",
        "src/main/java/com/android/purebilibili/feature/settings/screen/PluginsScreen.kt",
        "src/main/java/com/android/purebilibili/feature/settings/ui/CacheClearAnimation.kt",
        "src/main/java/com/android/purebilibili/feature/space/SpaceScreen.kt",
        "src/main/java/com/android/purebilibili/feature/video/player/VideoPlayerComponents.kt",
        "src/main/java/com/android/purebilibili/feature/video/screen/AudioModeScreen.kt",
        "src/main/java/com/android/purebilibili/feature/video/screen/TabletCinemaLayout.kt",
        "src/main/java/com/android/purebilibili/feature/video/screen/TabletVideoLayout.kt",
        "src/main/java/com/android/purebilibili/feature/video/screen/VideoContentSection.kt",
        "src/main/java/com/android/purebilibili/feature/video/screen/VideoDetailScreen.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/BottomInputBar.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/ChapterListPanel.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/CollectionRow.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/CollectionSheet.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/CommentInputBar.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/CommentInputDialog.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/DanmakuContextMenu.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/DanmakuSendDialog.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/DanmakuSettingsPanel.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/EmotePanelSheet.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/GlassComponents.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/InteractiveChoiceOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/PagesSelector.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/QualityMenu.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/RelatedVideoItem.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/ReplyComponents.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/SkeletonComponents.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/SpeedSelectionPanel.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/SponsorSkipUI.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/TwoFingerSpeedFeedbackOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/VideoActionFeedbackHost.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/VideoAspectRatio.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/VideoCommentSheetHost.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/VideoSettingsPanel.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/gesture/PlayerGestureHandler.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/AspectRatioPanel.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/BottomControlBar.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/CommandDanmakuOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/FullscreenPlayerOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/LandscapeDanmakuInput.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/LandscapeRightSidebar.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/LandscapeTopControlBar.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/LandscapeUpInfo.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/MiniPlayerOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/PersistentProgressBar.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/PortraitFullscreenOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/VideoPlayerOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/pager/PortraitDetailSheet.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/pager/PortraitVideoPager.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/section/AiSummarySection.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/section/VideoInfoSection.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/section/VideoNoteSection.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/section/VideoPlayerSection.kt",
        "src/main/java/com/android/purebilibili/feature/watchlater/WatchLaterScreen.kt"
    )

    /** 迁移到 AppMotionTokens 后从本表移除. */
    val MOTION_HITS: Set<String> = setOf(
        "src/main/java/com/android/purebilibili/feature/bangumi/BangumiScreen.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/DynamicSidebar.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/DynamicScreen.kt",
        "src/main/java/com/android/purebilibili/feature/following/FollowingListScreen.kt",
        "src/main/java/com/android/purebilibili/feature/home/components/miuix/InteractiveHighlight.kt",
        "src/main/java/com/android/purebilibili/feature/list/CommonListScreen.kt",
        "src/main/java/com/android/purebilibili/feature/login/LoginComponents.kt",
        "src/main/java/com/android/purebilibili/feature/login/LoginScreen.kt",
        "src/main/java/com/android/purebilibili/feature/onboarding/OnboardingBottomSheet.kt",
        "src/main/java/com/android/purebilibili/feature/search/SearchScreen.kt",
        "src/main/java/com/android/purebilibili/feature/settings/ui/CacheClearAnimation.kt",
        "src/main/java/com/android/purebilibili/feature/space/SpaceScreen.kt",
        "src/main/java/com/android/purebilibili/feature/video/screen/VideoContentSection.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/CelebrationAnimations.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/SponsorSkipUI.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/VideoCommentSheetHost.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/CommandDanmakuOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/FullscreenPlayerOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/VideoPlayerOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/pager/PortraitVideoPager.kt"
    )

    /** 迁移到 AppSurfaceTokens 后从本表移除. */
    val SURFACE_HITS: Set<String> = setOf(
        "src/main/java/com/android/purebilibili/feature/bangumi/BangumiDetailScreen.kt",
        "src/main/java/com/android/purebilibili/feature/bangumi/BangumiScreen.kt",
        "src/main/java/com/android/purebilibili/feature/bangumi/ui/components/BangumiFilterComponents.kt",
        "src/main/java/com/android/purebilibili/feature/bangumi/MyBangumiScreen.kt",
        "src/main/java/com/android/purebilibili/feature/category/CategoryScreen.kt",
        "src/main/java/com/android/purebilibili/feature/download/BatchDownloadDialog.kt",
        "src/main/java/com/android/purebilibili/feature/download/DirectorySelectionDialog.kt",
        "src/main/java/com/android/purebilibili/feature/download/DownloadListScreen.kt",
        "src/main/java/com/android/purebilibili/feature/download/DownloadQualityDialog.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/DynamicComponents.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/DynamicSidebar.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/DynamicTopBar.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/components/RepostDialog.kt",
        "src/main/java/com/android/purebilibili/feature/dynamic/DynamicScreen.kt",
        "src/main/java/com/android/purebilibili/feature/following/FollowingListScreen.kt",
        "src/main/java/com/android/purebilibili/feature/home/components/cards/GlassVideoCard.kt",
        "src/main/java/com/android/purebilibili/feature/list/CommonListScreen.kt",
        "src/main/java/com/android/purebilibili/feature/live/LivePlayerScreen.kt",
        "src/main/java/com/android/purebilibili/feature/message/ChatScreen.kt",
        "src/main/java/com/android/purebilibili/feature/onboarding/OnboardingBottomSheet.kt",
        "src/main/java/com/android/purebilibili/feature/onboarding/OnboardingScreen.kt",
        "src/main/java/com/android/purebilibili/feature/plugin/AdFilterPlugin.kt",
        "src/main/java/com/android/purebilibili/feature/plugin/EyeProtectionOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/plugin/HomeFeedAnonymizerPlugin.kt",
        "src/main/java/com/android/purebilibili/feature/plugin/SponsorBlockPlugin.kt",
        "src/main/java/com/android/purebilibili/feature/profile/OfficialWallpaperSheet.kt",
        "src/main/java/com/android/purebilibili/feature/profile/ProfileScreen.kt",
        "src/main/java/com/android/purebilibili/feature/profile/SplashWallpaperPickerSheet.kt",
        "src/main/java/com/android/purebilibili/feature/profile/WallpaperAdjustmentSheet.kt",

        "src/main/java/com/android/purebilibili/feature/search/SearchScreen.kt",
        "src/main/java/com/android/purebilibili/feature/search/SearchTrendingScreen.kt",
        "src/main/java/com/android/purebilibili/feature/search/TopicDetailScreen.kt",
        "src/main/java/com/android/purebilibili/feature/settings/screen/PluginsScreen.kt",
        "src/main/java/com/android/purebilibili/feature/settings/ui/CacheClearAnimation.kt",
        "src/main/java/com/android/purebilibili/feature/space/SpaceScreen.kt",
        "src/main/java/com/android/purebilibili/feature/video/player/VideoPlayerComponents.kt",
        "src/main/java/com/android/purebilibili/feature/video/screen/TabletCinemaLayout.kt",
        "src/main/java/com/android/purebilibili/feature/video/screen/TabletVideoLayout.kt",
        "src/main/java/com/android/purebilibili/feature/video/screen/VideoContentSection.kt",
        "src/main/java/com/android/purebilibili/feature/video/screen/VideoDetailScreen.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/BottomInputBar.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/CollectionSheet.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/CommentInputBar.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/CommentInputDialog.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/DanmakuSendDialog.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/EmotePanelSheet.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/FavoriteFolderSheet.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/GlassComponents.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/InteractiveChoiceOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/RelatedVideoItem.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/ReplyComponents.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/SkeletonComponents.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/components/TwoFingerSpeedFeedbackOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/overlay/VideoPlayerOverlay.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/pager/PortraitDetailSheet.kt",
        "src/main/java/com/android/purebilibili/feature/video/ui/section/VideoInfoSection.kt",
        "src/main/java/com/android/purebilibili/feature/watchlater/WatchLaterScreen.kt",
        "src/main/java/com/android/purebilibili/feature/web/WebViewScreen.kt"
    )
}
